### ISSUE TITLE
$CONDA_FORGE_SOURCE_URL default should use $TAG_TEMPLATE instead of $VERSION

### ISSUE THREAD

**Issue by igortg** [regro/rever#122]
I commonly use version tags in the format `v0.0.0` (suggested on GitHub docs), so I set `$TAG_TEMPLATE=v$VERSION` on my rever.xsh.

As `$CONDA_FORGE_SOURCE_URL` defaults to `$VERSION` variable, my _conda_forge_ activity can't find the source file on GitHub. Should we change the default to `$TAG_TEMPLATE`? (I could submit a PR for that if you like)

**Comment by scopatz** [comment]
Ahh good point @igortg! Thanks for bringing it up.  A PR would be awesome!
