### ISSUE TITLE
`hash_url` broken for libmagic

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#142]
when running `hash_url` on `ftp://ftp.astron.com/pub/file/file-5.33.tar.gz` I get an `'_io.BufferedReader' object has no attribute 'length'` error is that expected?

**Comment by scopatz** [comment]
Thanks @CJ-Wright - Do you have a traceback :wink: That might help!

**Comment by scopatz** [comment]
nm, I can reproduce
