### ISSUE TITLE
wrong sha256 in conda_forge activity

### ISSUE THREAD

**Issue by dougalsutherland** [regro/rever#173]
In https://github.com/conda-forge/arxiv-collector-feedstock/pull/1, rever put the wrong sha256 into the recipe somehow. `openssl sha256` on `dist/arxiv-collector-0.2.0.tar.gz` agrees with the PyPI one; don't know where `rever`'s came from.

**Comment by CJ-Wright** [comment]
What url are you using for the conda package? If you can you should use the uploaded tarball rather than the github made one.

**Comment by CJ-Wright** [comment]
I'm not certain, it should use the correct url @scopatz thoughts?

**Comment by scopatz** [comment]
See fix in https://github.com/scopatz/arxiv-collector/pull/1

**Comment by dougalsutherland** [comment]
Ah, cool, thanks.
