### ISSUE TITLE
Tarballs are not uploaded to PyPI

### ISSUE THREAD

**Issue by saraedum** [regro/rever#254]
It seems that rever is not uploading .tar.gz source distributions to PyPI when configured with

```
$PYPI_BUILD_COMMANDS = ['sdist', 'bdist_wheel']
```

I have this setting for two projects, and in both I need to manually `twine upload` the tarballs to PyPI.

Am I doing something wrong in these two rever scripts: [sage-flatsurf](https://github.com/flatsurf/sage-flatsurf/blob/master/rever.xsh) and [svgdigitizer](https://github.com/echemdb/svgdigitizer/blob/master/rever.xsh)?

For most users a wheel is perfectly fine. However, without the tarball, conda-forge does not pick up the new version automatically if its configured to download the tarball from PyPI.

**Comment by hadim** [comment]
I am also having the same issue.

So far the only solution is to remove the `pypi` activity from the rever config and use `python setup.py sdist && twine upload dist/*` instead.
