### ISSUE TITLE
how to undo a release?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#26]
It is mentioned in the docs header but not in the actual docs.

**Comment by scopatz** [comment]
There is a command line option (`-u`) but it does need more docs

**Comment by scopatz** [comment]
Thanks for reporting!

**Comment by CJ-Wright** [comment]
Thank you! (Leaving this open in case you want to issue docs PRs against it, feel free to close)

**Comment by CJ-Wright** [comment]
Put in docs via use patterns
