### ISSUE TITLE
reaver.xsh as dict?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#29]
Would a dict be a potentially better format for the environmental variables? This way they could be loaded from a more standard format (json, yaml, pure python?). This would also make these files more friendly to other applications which may not speak xonsh.

**Comment by scopatz** [comment]
Let's hold off on different interfaces until the core functionality is there and working.  Also, these env vars can be set from outside of rever.  So if you have a dict of envvar names you want to export, that can already be done.

**Comment by CJ-Wright** [comment]
I have listened to the wisdom of the xonsh and it spoke to me of the goodness of environmental variables (as opposed to dicts).
