### ISSUE TITLE
Does reaver tag include a version bump?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#38]

**Comment by scopatz** [comment]
Version bump is a different activity, if that was your question... http://www.ergs.sc.edu/rever-docs/activities.html#versionbump  Do you mean does it depend on version bump?

**Comment by CJ-Wright** [comment]
If I want to 1) update the version and 2) release that is that a two command process or just one?

**Comment by scopatz** [comment]
command or activity?

**Comment by CJ-Wright** [comment]
command, although if there is a difference we should probs make a warning somewhere

**Comment by scopatz** [comment]
I would write the rever.xsh file as follows:

```sh
$ACTIVITIES = ['version_bump', 'tag']
$VERSION_BUMP_PATTERNS = [...]
```

Then both activities will be run when you execute `rever X.Y`

**Comment by CJ-Wright** [comment]
Awesome!
