### ISSUE TITLE
DOC: Changlog does not explain the usage pattern

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#49]
There is a use pattern to get `Changelog` to work properly. 

All PRs must have an addition to the `news` folder as a new file (or some other user defined file). During the release process the news info get collated and moved into a changlog file.

More broadly we may want to capture some critical use patterns in its own `rever` docs file. These patterns are not _formally_ part of the `rever` code base but are needed to make the most of the software.

**Comment by scopatz** [comment]
Thanks for reporting this @CJ-Wright

**Comment by CJ-Wright** [comment]
Closed by various PRs into the docs
