### ISSUE TITLE
ENH: nicely handle white space for version_bump

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#50]
It is very possible that we will want to have whitespace in the version replacement (eg it's in an indented block (setup.py?)). Currently this white space must be hard coded into the `rever.xsh` file (see rever's file for an example). This is rather inelegant and could cause tons of problems. Would it be possible to keep track of this white space and maintain it upon replacement?

**Comment by scopatz** [comment]
For clarification, you mean leading whitespace? Or all whitespace?

**Comment by CJ-Wright** [comment]
I meant leading, although other would be ok too.

**Comment by scopatz** [comment]
Other would be much harder.

**Comment by CJ-Wright** [comment]
We can fix problems as people yell about them, I am good with just leading whitespace.
