### ISSUE TITLE
get linter from xonsh

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#55]
Would it be possible to make the xonsh linter (which checks for news entries) and lambda stuff more broadly available?
This would be very helpful to bringing rever using projects into the `news` -> `CHANGELOG` workflow.
Can we subscribe other repos to the xonsh lambda instance?
If not can we provide instructions for users to set up their own lambda driven linter?

**Comment by CJ-Wright** [comment]
@astronouth7303 Would you be able to comment on this? I think you did a lot of the work on the xonsh linting setup right?

**Comment by astronouth7303** [comment]
All of the code is https://github.com/xonsh/prlint including the build tooling. I didn't document how to do the initial setup because it felt like a just-for-us hack.

**Comment by scopatz** [comment]
Yeah, there has been some discussion around the office about this with @asmeurer and @FlanFlanagan too

**Comment by scopatz** [comment]
The linter itself seems like it can / should be a different regro project.  Are you OK with closing this for now @CJ-Wright
