### ISSUE TITLE
Conda-forge thinks it's done when it isn't

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#85]
I just tagged regolith 0.1.6 but it thinks that conda_forge has already been done, when it hasn't done anything.

**Comment by scopatz** [comment]
did you remove the log prior to running?

**Comment by CJ-Wright** [comment]
No, I didn't but if that is the "official answer" we might want to automate things. I also like having the log, since it allows me to go back and see what happened.

**Comment by scopatz** [comment]
That isn't the official answer, that is a temporary hack :)

**Comment by CJ-Wright** [comment]
*Whew* I was a bit worried. (I'm not so worried about the regolith conda-forge being out of date, since we just fixed the version number in the setup.py, although I will put up the conda-forge PR if you want)

**Comment by scopatz** [comment]
You can fix this if you want.  All the code for figuring out which activities have already been run is in main.xsh. It basically just needs to also take into account the version number

**Comment by CJ-Wright** [comment]
Hmm ok.

**Comment by CJ-Wright** [comment]
How do we keep track of the version number now?

**Comment by scopatz** [comment]
Each log entry should have the version number in it.

**Comment by CJ-Wright** [comment]
Here is what I have from regolith
```python
{"activity":"conda_forge","category":"activity-start","message":"starting activity conda_forge","rev":"8aad6145cb77d6628decaec451ead230ae2c874f","timestamp":1510805600.645067}
{"activity":"conda_forge","category":"activity-end","data":{"start_rev":"8aad6145cb77d6628decaec451ead230ae2c874f"},"message":"activity conda_forge complete","rev":"8aad6145cb77d6628decaec451ead230ae2c874f","timestamp":1510805667.4755368}
{"activity":"version_bump","category":"activity-start","message":"starting activity version_bump","rev":"53e2ba8dcee4fb8248425860b9adf6741dfdcc86","timestamp":1511138023.8658211}
{"activity":"version_bump","category":"activity-end","data":{"start_rev":"53e2ba8dcee4fb8248425860b9adf6741dfdcc86"},"message":"activity version_bump complete","rev":"f968a659eb4d29f4fd0951da5766277dae6a44a2","timestamp":1511138023.8821657}
```

I don't think there is a version there.

**Comment by scopatz** [comment]
Ahh damn, that is why it is failing then.  the version needs to be added then, so we can filter based on it.
